name: PR-CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup
        run: ./.github/setup.sh
      - name: Build
        run: ./.github/ci.sh
        
