name: PR-CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup
        run: ./.github/setup.sh
      - name: Check
        run: ./.github/ci.sh

  formatting-check:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Formatting
      uses: jidicula/clang-format-action@4726374d1aa3c6aecf132e5197e498979588ebc8
      with:
        clang-format-version: '19'
        check-path: './.'
        fallback-style: 'Google' # optional
        exclude-regex: '(vendor|matlab)'
        
